# Generated by Django 4.2.4 on 2023-08-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('use', models.CharField(max_length=255)),
                ('reception', models.CharField(max_length=255)),
                ('select', models.CharField(max_length=255)),
                ('recruit', models.CharField(max_length=255)),
                ('application', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('reserve', models.CharField(max_length=255)),
                ('call', models.CharField(max_length=255)),
                ('image', models.URLField()),
            ],
        ),
    ]
