# Generated by Django 4.2.4 on 2023-08-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='siteUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='typeDetail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
