# Generated by Django 4.2.4 on 2023-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_facilitytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacilityTest',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='application',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='call',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='image',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='location',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='reception',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='recruit',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='reserve',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='select',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='target',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='use',
        ),
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
