# Generated by Django 4.2.4 on 2023-08-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_facility_siteurl_facility_type_facility_typedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
